spring.datasource.url=jdbc:postgresql://localhost:5432/clib_db?currentSchema=springbatch503_schma
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.batch=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.initialize-schema=never

# Spring Batch ????? ?? SQL(DML) ??
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

# ???? SQL? ??
logging.level.org.springframework.jdbc=DEBUG

# Spring Batch ???(JobRepository) ?? ??? ??
logging.level.org.springframework.batch.core.repository=DEBUG

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=kr.co.wlife.fac.jhb.batch.item

#logging.level.kr.co.wlife.fac.jhb.batch.mapper=debug
logging.level.kr.co.wlife.fac.jhb.batch.mapper=info